version: '2.0'
services:
  sonarqube:
    image: sonarqube:7.5-community
    expose:
      - 9000
    ports:
      - "8090:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=sonar
#    volumes:
#      - /opt/sonarqube/conf:/opt/sonarqube/conf
#      - /opt/sonarqube/data:/opt/sonarqube/data
#      - /opt/sonarqube/extensions:/opt/sonarqube/extensions
    depends_on:
      - mysql
  mysql:
   image: mysql:5
   environment:
     MYSQL_ROOT_PASSWORD: sonar
     MYSQL_DATABASE: sonar
   ports:
     - "3306:3306"
   container_name: my_mysql
   volumes:
     - /home/mtadmin123/docker/sonar/sql/:/docker-entrypoint-initdb.d
     - /home/mtadmin123/docker/sonar/data_storage:/var/lib/mysql
